### ISSUE TITLE
requirements.txt missing in _templates folder

### ISSUE THREAD

**Issue by Bronzila** [automl/automl_template#10]
Add requirements.txt file to _templates folder.

**Comment by benjamc** [comment]
:+1: Was removed in commit 5a56c6e93b55b2f764ef50eb08ca061978b25e6f "Small fixes".

**Comment by benjamc** [comment]
It actually stops the process of generating the repository. Removing this [line](https://github.com/automl/automl_template/blob/5dcbed3e20b6297bfaa1369d19076d82c4e31427/generate.py#L36) fixes it.:)
