### ISSUE TITLE
Delete original README.md in generate.py

### ISSUE THREAD

**Issue by Bronzila** [automl/automl_template#9]
When running generate.py an error is thrown, because the orginal README.md can not be overwritten by the generated one. Therefore delete the original README.md before copying the generated one.

**Comment by eddiebergman** [comment]
Ahh turns out this is window's specific but good to know about:

https://docs.python.org/3/library/pathlib.html#pathlib.Path.rename

I guess we want `replace`

https://docs.python.org/3/library/pathlib.html#pathlib.Path.replace
